-- ============================================================
-- ClickHouse Database Initialization
-- Fraud Detection Platform
-- ============================================================

CREATE DATABASE IF NOT EXISTS fraud_detection;

-- ============================================================
-- Main Transactions Table (ReplacingMergeTree Engine)
-- Stores all processed transactions with risk scores.
-- Uses ReplacingMergeTree to deduplicate by transaction_id
-- on checkpoint recovery / exactly-once semantics.
-- ============================================================
CREATE TABLE IF NOT EXISTS fraud_detection.transactions
(
    transaction_id   String,
    account_id       String,
    card_id          String DEFAULT '',
    event_time       DateTime64(3),
    amount           Float64,
    event_type       String,
    channel          String DEFAULT '',
    latitude         Float64,
    longitude        Float64,
    merchant_id      String,
    status           String DEFAULT 'PENDING',
    ml_score         Float64 DEFAULT 0.0,
    rule_triggered   String DEFAULT '',
    is_fraud         UInt8 DEFAULT 0,
    ground_truth_is_fraud UInt8 DEFAULT 0,
    decision         String DEFAULT 'APPROVE',
    decision_source  String DEFAULT '',
    combined_score   Float64 DEFAULT 0.0,
    produced_at      DateTime64(3),
    decided_at       DateTime64(3),
    processing_time  DateTime64(3) DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(decided_at)
PARTITION BY toYYYYMMDD(event_time)
ORDER BY (transaction_id)
TTL toDateTime(event_time) + INTERVAL 90 DAY
SETTINGS index_granularity = 8192;

ALTER TABLE fraud_detection.transactions
    ADD COLUMN IF NOT EXISTS ground_truth_is_fraud UInt8 DEFAULT 0 AFTER is_fraud;

-- ============================================================
-- Fraud Alerts Table (ReplacingMergeTree Engine)
-- Stores all fraud alerts generated by CEP, Rules, and ML.
-- Uses ReplacingMergeTree(alert_time) to deduplicate final alerts
-- by stable alert_id on Flink checkpoint recovery.
-- ============================================================
CREATE TABLE IF NOT EXISTS fraud_detection.fraud_alerts
(
    alert_id         String,
    transaction_id   String,
    account_id       String,
    alert_type       String,
    alert_source     String,
    severity         String,
    score            Float64,
    details          String,
    matched_events   String,
    event_time       DateTime64(3),
    alert_time       DateTime64(3) DEFAULT now64(3)
)
ENGINE = ReplacingMergeTree(alert_time)
PARTITION BY toYYYYMMDD(event_time)
ORDER BY (alert_id)
TTL toDateTime(alert_time) + INTERVAL 180 DAY
SETTINGS index_granularity = 8192;

-- ============================================================
-- Materialized View: Transaction Throughput per Minute
-- ============================================================
CREATE TABLE IF NOT EXISTS fraud_detection.tx_throughput
(
    window_start     DateTime,
    tx_count         AggregateFunction(count, UInt64),
    total_amount     AggregateFunction(sum, Float64),
    fraud_count      AggregateFunction(sumIf, UInt8, UInt8)
)
ENGINE = AggregatingMergeTree()
ORDER BY window_start;

CREATE MATERIALIZED VIEW IF NOT EXISTS fraud_detection.tx_throughput_mv
TO fraud_detection.tx_throughput
AS
SELECT
    toStartOfMinute(event_time) AS window_start,
    countState() AS tx_count,
    sumState(amount) AS total_amount,
    sumIfState(is_fraud, is_fraud = 1) AS fraud_count
FROM fraud_detection.transactions
GROUP BY window_start;

-- ============================================================
-- Materialized View: Alerts by Type Aggregation
-- ============================================================
CREATE TABLE IF NOT EXISTS fraud_detection.alerts_by_type
(
    alert_date       Date,
    alert_type       String,
    alert_source     String,
    alert_count      AggregateFunction(count, UInt64),
    avg_score        AggregateFunction(avg, Float64)
)
ENGINE = AggregatingMergeTree()
ORDER BY (alert_date, alert_type, alert_source);

CREATE MATERIALIZED VIEW IF NOT EXISTS fraud_detection.alerts_by_type_mv
TO fraud_detection.alerts_by_type
AS
SELECT
    toDate(alert_time) AS alert_date,
    alert_type,
    alert_source,
    countState() AS alert_count,
    avgState(score) AS avg_score
FROM fraud_detection.fraud_alerts
GROUP BY alert_date, alert_type, alert_source;

-- ============================================================
-- Materialized View: Fraud by Geography
-- ============================================================
CREATE TABLE IF NOT EXISTS fraud_detection.fraud_by_geo
(
    geo_date         Date,
    lat_bucket       Float64,
    lon_bucket       Float64,
    fraud_count      AggregateFunction(count, UInt64),
    total_amount     AggregateFunction(sum, Float64)
)
ENGINE = AggregatingMergeTree()
ORDER BY (geo_date, lat_bucket, lon_bucket);

CREATE MATERIALIZED VIEW IF NOT EXISTS fraud_detection.fraud_by_geo_mv
TO fraud_detection.fraud_by_geo
AS
SELECT
    toDate(event_time) AS geo_date,
    round(latitude, 0) AS lat_bucket,
    round(longitude, 0) AS lon_bucket,
    countState() AS fraud_count,
    sumState(amount) AS total_amount
FROM fraud_detection.transactions
WHERE is_fraud = 1
GROUP BY geo_date, lat_bucket, lon_bucket;

-- ============================================================
-- Materialized View: End-to-End Latency Stats per Minute
-- ============================================================
CREATE TABLE IF NOT EXISTS fraud_detection.latency_stats
(
    window_start     DateTime,
    avg_latency_ms   AggregateFunction(avg, Float64),
    max_latency_ms   AggregateFunction(max, Float64),
    tx_count         AggregateFunction(count, UInt64)
)
ENGINE = AggregatingMergeTree()
ORDER BY window_start;

CREATE MATERIALIZED VIEW IF NOT EXISTS fraud_detection.latency_stats_mv
TO fraud_detection.latency_stats
AS
SELECT
    toStartOfMinute(decided_at) AS window_start,
    avgState(toFloat64(dateDiff('millisecond', produced_at, decided_at))) AS avg_latency_ms,
    maxState(toFloat64(dateDiff('millisecond', produced_at, decided_at))) AS max_latency_ms,
    countState() AS tx_count
FROM fraud_detection.transactions
WHERE produced_at > '1970-01-02'
  AND decided_at > '1970-01-02'
GROUP BY window_start;
