apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    uid: clickhouse
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      defaultDatabase: fraud_detection
      username: default
    secureJsonData:
      password: clickhouse123
    editable: true
