package com.frauddetection.model;

import java.io.Serializable;
import java.util.UUID;

/**
 * FraudAlert — represents an alert generated by CEP, Rules Engine, or ML
 * scoring.
 *
 * <p>
 * Used in two ways:
 * <ol>
 * <li>Embedded in Transaction (cepAlerts, ruleAlertObjects) for Decision
 * Engine</li>
 * <li>Standalone record written to ClickHouse fraud_alerts table and Kafka
 * fraud-alerts topic</li>
 * </ol>
 */
public class FraudAlert implements Serializable {

    private static final long serialVersionUID = 1L;

    private String alertId;
    private String transactionId;
    private String accountId;
    private String alertType; // e.g., ACCOUNT_TAKEOVER, MICRO_TRANSACTIONS, IMPOSSIBLE_TRAVEL
    private String alertSource; // CEP, RULES_ENGINE, ML_SCORING
    private String severity; // CRITICAL, HIGH, MEDIUM, LOW
    private double score;
    private String details;
    private String matchedEvents;
    private long eventTime;

    public FraudAlert() {
        this.alertId = UUID.randomUUID().toString();
    }

    public FraudAlert(String transactionId, String accountId, String alertType,
            String alertSource, String severity, double score,
            String details, String matchedEvents, long eventTime) {
        this.alertId = UUID.randomUUID().toString();
        this.transactionId = transactionId;
        this.accountId = accountId;
        this.alertType = alertType;
        this.alertSource = alertSource;
        this.severity = severity;
        this.score = score;
        this.details = details;
        this.matchedEvents = matchedEvents;
        this.eventTime = eventTime;
    }

    // ── Getters & Setters ─────────────────────────────────
    public String getAlertId() {
        return alertId;
    }

    public void setAlertId(String alertId) {
        this.alertId = alertId;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getAlertType() {
        return alertType;
    }

    public void setAlertType(String alertType) {
        this.alertType = alertType;
    }

    public String getAlertSource() {
        return alertSource;
    }

    public void setAlertSource(String alertSource) {
        this.alertSource = alertSource;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        this.score = score;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public String getMatchedEvents() {
        return matchedEvents;
    }

    public void setMatchedEvents(String matchedEvents) {
        this.matchedEvents = matchedEvents;
    }

    public long getEventTime() {
        return eventTime;
    }

    public void setEventTime(long eventTime) {
        this.eventTime = eventTime;
    }

    @Override
    public String toString() {
        return "FraudAlert{" +
                "alertId='" + alertId + '\'' +
                ", alertType='" + alertType + '\'' +
                ", alertSource='" + alertSource + '\'' +
                ", severity='" + severity + '\'' +
                ", score=" + score +
                ", accountId='" + accountId + '\'' +
                '}';
    }
}
